name: Devcontainer CI

# ignore prs/commits that don't touch those files
on:
  pull_request:
    paths:
      - ".devcontainer/**"
  push:
    branches: [main]
    paths:
      - ".devcontainer/**"

jobs:
  build:
    name: Build devcontainer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build devcontainer
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          runCmd: |
            set -x
            rustup show
            go version
            nix --version
            sccache --show-stats
            cargo nextest --version
            just --version
            gh --version
